In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [51]:
df=sns.load_dataset("iris")

In [52]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [53]:
X=df.iloc[: , :-1]
y=df.iloc[ : ,-1:]

In [54]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=.2,random_state=42)

In [55]:
# Define the parameter grid for KNN (specify a range of K values to try)
param_grid = {'n_neighbors': np.arange(1, 21)}  # Try K values from 1 to 20
knn = KNeighborsClassifier()

In [56]:
grid_search = GridSearchCV(knn, param_grid, cv=8, scoring='accuracy')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=8, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])},
             scoring='accuracy')

In [57]:
grid_search.best_params_

{'n_neighbors': 11}

In [58]:
# Print the best value of K and its corresponding accuracy score
print("Best K value:", grid_search.best_params_['n_neighbors'])
print("Best accuracy score:", grid_search.best_score_)

Best K value: 11
Best accuracy score: 0.9583333333333333


In [59]:
classifier=KNeighborsClassifier(n_neighbors=6, algorithm="auto")
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [60]:
from sklearn.datasets import load_boston

In [61]:
boston = load_boston()

In [62]:
df = pd.DataFrame(data=boston.data, columns=boston.feature_names)
df['target'] = boston.target

In [63]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [64]:
X=df.iloc[: , :-1]
y=df.iloc[ : ,-1:]

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

In [66]:
from sklearn.neighbors import KNeighborsRegressor
regressor= KNeighborsRegressor(n_neighbors=5,algorithm="auto")

In [67]:
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [68]:
y_pred=regressor.predict(X_test)

In [69]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)

In [70]:
mse,mae,rmse

(25.860125490196076, 3.6639215686274507, 5.0852851926117255)

In [71]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
score

0.6473640882039258

In [72]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_scaled=scalar.fit_transform(X)

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [74]:
from sklearn.neighbors import KNeighborsRegressor
regressor= KNeighborsRegressor(n_neighbors=5,algorithm="auto")

In [75]:
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [76]:
y_pred=regressor.predict(X_test)

In [77]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 20.65732549019608


In [78]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
score

0.7183109257429846

In [80]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset
iris = load_iris()
X, y = iris.data, iris.target

# Step 2: Split the dataset into features (X) and target variable (y)
# No need to split the dataset since we'll use train_test_split later

# Step 3: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Initialize the KNN classifier with weighted voting
knn_classifier = KNeighborsClassifier(weights='distance')  # Use weighted voting

# Step 5: Fit the classifier to the training data
knn_classifier.fit(X_train, y_train)

# Step 6: Make predictions on the testing data
y_pred = knn_classifier.predict(X_test)

# Step 7: Evaluate the performance of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


In [85]:
# Example usage
point1 = [1, 2, 3]
point2 = [4, 5, 6]

# Calculate Euclidean distance
euclidean_dist = euclidean_distance(point1, point2)
print("Euclidean distance:", euclidean_dist)

# Calculate Manhattan distance
manhattan_dist = manhattan_distance(point1, point2)
print("Manhattan distance:", manhattan_dist)


Euclidean distance: 5.196152422706632
Manhattan distance: 9


In [82]:
from sklearn.preprocessing import StandardScaler

def standardize_features(X_train, X_test):
    """
    Standardize the features using StandardScaler.

    Parameters:
    - X_train: Training features.
    - X_test: Testing features.

    Returns:
    - Standardized training features and testing features.
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled, X_test_scaled


In [83]:
import numpy as np

def euclidean_distance(point1, point2):
    """
    Calculate the Euclidean distance between two points.

    Parameters:
    - point1: Coordinates of the first point (array-like).
    - point2: Coordinates of the second point (array-like).

    Returns:
    - Euclidean distance between the two points.
    """
    return np.sqrt(np.sum((np.array(point1) - np.array(point2)) ** 2))


In [84]:
def manhattan_distance(point1, point2):
    """
    Calculate the Manhattan distance between two points.

    Parameters:
    - point1: Coordinates of the first point (array-like).
    - point2: Coordinates of the second point (array-like).

    Returns:
    - Manhattan distance between the two points.
    """
    return np.sum(np.abs(np.array(point1) - np.array(point2)))
